[package]
name = "donnager"
version = "0.1.1"
description = "Blazingly fast astrodynamics calculations in Rust"
license = "MIT"
keywords = ["astrodynamics", "astronomy", "satellites"]
repository = "https://github.com/Thomas-Oz-Dunn/donnager"

edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "donnager"

[[bin]]
name = "launch_sim"
path = "src/launch_sim/main.rs"

[[bin]]
name = "n_body_sim"
path = "src/n_body_sim/main.rs"

[dependencies]
nalgebra = "0.31.4"
plotters = "0.3.4"
chrono = "0.4.23"