[package]
name = "donnager"
version = "0.1.0"
description = "Blazingly fast astrodynamics calculations in Rust"
license = "MIT"
keywords = ["astrodynamics", "astronomy", "satellites"]
repository = "https://github.com/Thomas-Oz-Dunn/donnager"

edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.4"
plotters = "0.3.4"
chrono = "0.4.23"